# Generated by Django 3.2.15 on 2022-10-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='someone', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
