# Generated by Django 3.2.15 on 2023-10-22 08:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='from_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='to_date',
            field=models.DateTimeField(default=datetime.date(2023, 12, 31)),
        ),
    ]
